0x0c

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,8 +2,8 @@
 #checking for command-line argument
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
 
 # Assigning Arguments to variables
@@ -20,7 +20,7 @@ scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$userna
 # Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-  echo "FILE TRANSFER WAS SUCCESSFUL"
+	echo "FILE TRANSFER WAS SUCCESSFUL"
 else
-  echo "FILE TRANSFER FAILED"
+	echo "FILE TRANSFER FAILED"
 fi
